### ISSUE TITLE
Dynamic filter options in facet panel

### ISSUE THREAD

**Issue by aswallace** [Duke-MatSci/materialsmine#119]
Facet panel in explorer should load different filtering options depending on which tab is selected (article, chart, etc.) See [Mike's UI ppt](https://github.com/Duke-MatSci/Learning/blob/main/2021-12_UI%20Mockups.pptx)

See also [Scholars@Duke](https://scholars.duke.edu/scholars_search/?advanced=false&allWords=materials&atLeastOne=&exactMatch=&filter=publications&noMatch=&start=0) for an example
<img width="1001" alt="Screen Shot 2022-02-17 at 3 33 45 PM" src="https://user-images.githubusercontent.com/24441706/154589421-bb99fc41-dd99-41a3-9a81-eba985d3a14f.png">

**Comment by tholulomo** [comment]
This ticket requires a TD ticket that focuses on a tab-focused facet filter
