### ISSUE TITLE
Write test for PixelUnit.js

### ISSUE THREAD

**Issue by roryschadler** [Duke-MatSci/materialsmine#149]
Tests of components with `<canvas>` elements get complicated, due to the way `jest` and its outdated version of `jsdom` handle them.

The PixelUnit component is one of those, and one of its tests was causing CI to fail. It's been renamed to [`pixelunit.spec.txt`](https://github.com/Duke-MatSci/materialsmine/blob/2af164a7d4cb5dd7ac6416d0827d213625b73812/app/tests/unit/pages/metamine/pixelunit.spec.txt).

**Comment by tholulomo** [comment]
Task completed
