### ISSUE TITLE
Choose VueSocketIO or SocketIO

### ISSUE THREAD

**Issue by roryschadler** [Duke-MatSci/materialsmine#151]
> We shouldn't need this if we are using vue-socket.io. We can create a TD ticket for this fix. At implementation, Atul was just playing with different scenarios but didn't have enough time to fix those before he left.

_Originally posted by @tholulomo in https://github.com/Duke-MatSci/materialsmine/pull/142#discussion_r835441143_

**Comment by roryschadler** [comment]
Choose one implementation over the other, and remove unused references/dependencies

**Comment by tholulomo** [comment]
Task completed
