### ISSUE TITLE
Migrate style sheets into app container

### ISSUE THREAD

**Issue by mjpalmeri** [Duke-MatSci/materialsmine#18]
Migrate stylesheets from the nanomine src directory repo into the asset folder. The folder structure should be app/src/assets/CSS.

The following will be required to consider the task done:

- Folder structure as indicated above should be maintained
- All files and folders from origin should be in the new location
- Import into provided sample component and test
- Add vue materials

Epic: #17

**Comment by aswallace** [comment]
Potential issue: We are using Vue3, which Vue Material doesn't support yet. In the previous version we were using Vue2.6
