### ISSUE TITLE
MRS Tutorial Feedback

### ISSUE THREAD

**Issue by mjpalmeri** [Duke-MatSci/materialsmine#201]
This story contains bug fixes, suggested improvements, etc based on feedback from participants at the MRS 2022 Spring meeting NanoMine Tutorial.  See 5/17/22 NanoMine meeting notes (https://docs.google.com/document/d/1CpA8AT6bs2gzmAyDlaRhOLlM5HJkbyZdOPrc1N5quR4/edit) for more details.

- [x] #202
- [x] #203
- [x] #204
- [x] #205
- [x] #206
- [x] #207
- [x] #208
- [ ] #209
- [x] #210
- [x] #212
- [ ] #213
- [x] #214
- [x] #215
- [x] #216
- [x] #220

**Comment by tholulomo** [comment]
Closing as complete. Ticket #209 and #213 will migrated to a different story
