### ISSUE TITLE
Handle TIF images

### ISSUE THREAD

**Issue by aswallace** [Duke-MatSci/materialsmine#270]
Need to be able to handle TIF and TIFF images for XML spreadsheet upload
- If user selects tif/tiff, filter them and notify user that we don't accept those files
- Provide link to convert to png
- User must be able to download the new png and add to xml upload supplementary files

**Comment by tholulomo** [comment]
This ticket will require #229 merge. Changing its milestone

**Comment by tholulomo** [comment]
Task completed
