### ISSUE TITLE
Broken image links on Visualization Gallery page

### ISSUE THREAD

**Issue by aswallace** [Duke-MatSci/materialsmine#291]
There are multiple instances where images in the gallery (on QA and local, not prod) don't show up / links are broken.
This is occurring for a few different reasons:

- [ ] Three files appear to be curation tests and don't actually point to real files 
    - http://localhost/explorer/images/58e5d305e74a1d1ac2fc47ef/%2Fapi%2Ffiles%2Fundefined , http://localhost/explorer/images/58e6c36ee74a1d1ac2fc4802/%2Fapi%2Ffiles%2Fundefined , http://localhost/explorer/images/58e71bcce74a1d36e1b77091/%2Fapi%2Ffiles%2Fundefined
- [ ] Four files were incorrectly curated and point to .zip files that contain multiple .xml files instead of a single file
    - http://localhost/explorer/images/5a1dec03e74a1d03cd1e6317/%2Fapi%2Ffiles%2F59616da6e74a1d5e0d19555d , http://localhost/explorer/images/5a1dec03e74a1d03cd1e6317/%2Fapi%2Ffiles%2F59616dbfe74a1d5e0d195561 , http://localhost/explorer/images/5a1dec03e74a1d03cd1e6317/%2Fapi%2Ffiles%2F59616db3e74a1d5e0d19555f , http://localhost/explorer/images/5a1dec03e74a1d03cd1e6317/%2Fapi%2Ffiles%2F59616dcde74a1d5e0d195563
- [ ] Two point to null file IDs
    - http://localhost/explorer/images/5a6f9ce4e74a1d322f17cf9f/%2Fapi%2Ffiles%2Fundefined, http://localhost/explorer/images/5a6f9b4de74a1d322f17c5bc/%2Fapi%2Ffiles%2Fundefined
- [ ] There are others further on that I haven't had a chance to look at yet, I'll keep looking later

I'm not sure the best way to address this... we might need to go through and manually fix these individually

**Comment by tholulomo** [comment]
This task is completed
