### ISSUE TITLE
Check charts in gallery 

### ISSUE THREAD

**Issue by aswallace** [Duke-MatSci/materialsmine#377]
**Describe the task**
Now that charts are editable, check them individually to make sure they still work.
Update list below as needed

**List of charts that need fixing:**

- [x] DataVoyager Variant: Pleasantville http://localhost/explorer/chart/view/7a13349da71a5123  -- needs `$schema`. ~However, even when fixed, this chart doesn't do what the description says... We might need to ask Mike about this one~ (Update: this is just a DataVoyager variant whose description wasn't modified)
- [x] Tradeoff plot http://localhost/explorer/chart/view/9316ed4a6947cebb -- error in `BIND` with `?VolFrac`
- [x] Big Data vs. Broad Data http://localhost/explorer/chart/editor/edit/d7895c41d76aaf56 -- needs a re-write, query times out Fuseki
- [ ] A Material by Any Other Name http://localhost/explorer/chart/editor/edit/d36e76d3c24e345e -- needs a re-write, query times out Fuseki. Also has a `BIND` error. (I already have a fix for this one but just need to edit it on QA)
- [ ] Breakdown of Processing Procedures and Steps http://localhost/explorer/chart/view/0ef84722e52cacda -- not sure yet but probably needs a re-write. Original query takes 10 min to load

**Comment by tholulomo** [comment]
This is still an on-going effort. The chart referenced here have been fixed. Moving the remain two to a separate ticket
