### ISSUE TITLE
Remove Authentication Requirement for SPARQL

### ISSUE THREAD

**Issue by jpmccu** [Duke-MatSci/materialsmine#421]
**Is your feature request related to a problem? Please describe.**
I am developing a method for summarizing knowledge graphs using a set of SPARQL queries. I would like to create a jupyter notebook that can demonstrate the process, and would like to use it on the materialsmine KG. However, authenticating makes that difficult. Now that we have a timeout in place for the SPARQL endpoint, we should be able to open the endpoint up to the public again.

**Comment by tholulomo** [comment]
We provide a JWT token for secure access, which can be conveniently copied from the portal’s home page within the application. To enhance system security and mitigate vulnerabilities, we have discontinued open-ended connections to KG, considering the potential intensity and resource demands of certain queries.
