### ISSUE TITLE
Setup Fuseki with Docker

### ISSUE THREAD

**Issue by tholulomo** [Duke-MatSci/materialsmine#43]
Apache Fuseki is an ultra-high-performance graph database supporting Blueprints and RDF/SPARQL APIs. Using Apache Fuseki with Docker allows us to have a portable Graph database that can be run on any server platform without having to worry about its configuration. We can use Docker container images to make the Apache Fuseki database deployment process more efficient and straightforward.

Task:
1. Create a Fuseki image & add it to the list of existing containers
2. Make Database accessible to other containers
3. Port mapping
4. Volume mount data

**Comment by jpmccu** [comment]
This should be fuseki, not blazegraph.

**Comment by tholulomo** [comment]
@jpmccu This is for the current service in QA as we have it (I believe this is temporary). We are definitely creating one for Fuseki next week I believe. We just want to be able to transfer as is current Blazegraph™ data.

**Comment by tholulomo** [comment]
> This should be fuseki, not blazegraph.

Updated ticket to fuseki!
